/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface Posts {
  'created'?: string;
  'id'?: string;
  'json'?: Object | null;
  'text'?: string | null;
  'updated'?: string;
}
export interface Users {
  'avatar'?: string | null;
  'created'?: string;
  'email'?: string;
  'emailVisibility'?: boolean;
  'id'?: string;
  'lastResetSentAt'?: string;
  'lastVerificationSentAt'?: string;
  'name'?: string | null;
  'passwordHash': string;
  'tokenKey': string;
  'updated'?: string;
  'username': string;
  'verified'?: boolean;
}
export interface DB { 
 
   posts: Posts; 
 
   users: Users; 

 } 
